<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'car_name' => 'Toyota Corolla',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 50.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 1,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Honda Civic',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 45.00,
                'type' => 'Manual',
                'air_conditioning' => true,
                'carcompany_id' => 2,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Ford Mustang',
                'passenger_num' => 4,
                'door_num' => 2,
                'price_day' => 85.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 3,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Chevrolet Impala',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 55.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 4,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Nissan Altima',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 50.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 5,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Toyota Camry',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 60.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 1,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Jeep Wrangler',
                'passenger_num' => 4,
                'door_num' => 2,
                'price_day' => 100.00,
                'type' => 'Manual',
                'air_conditioning' => true,
                'carcompany_id' => 2,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Ford F-150',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 90.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 3,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Toyota Rav4',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 65.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 4,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Hyundai Sonata',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 50.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 5,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Jeep Grand Cherokee',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 95.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 1,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Chevrolet Tahoe',
                'passenger_num' => 7,
                'door_num' => 4,
                'price_day' => 125.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 2,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Nissan Maxima',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 60.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 3,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Ford Fusion',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 55.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 4,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Dodge Charger',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 75.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 5,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Toyota Highlander',
                'passenger_num' => 8,
                'door_num' => 4,
                'price_day' => 110.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 1,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Ford Escape',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 65.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 2,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Nissan Rogue',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 55.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 3,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Chevrolet Equinox',
                'passenger_num' => 5,
                'door_num' => 4,
                'price_day' => 60.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 4,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'car_name' => 'Toyota Sienna',
                'passenger_num' => 7,
                'door_num' => 4,
                'price_day' => 95.00,
                'type' => 'Auto',
                'air_conditioning' => true,
                'carcompany_id' => 5,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
        ];
        DB::table('cars')->insert($data);
    }
}
