<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HotelsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'name' => 'Ritz Carlton Tokyo',
                'location' => 'Tokyo, Japan - 9 Chome-7-1 Akasaka, Minato City',
                'description' => 'A luxurious hotel with stunning views of Tokyo Tower and the city skyline',
                'average_rate' => 4.8,
                'phone' => '+81 3-3423-8000',
                'website' => ' https://www.ritzcarlton.com/en/hotels/japan/tokyo',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The Plaza Hotel',
                'location' => 'New York City, USA - 768 5th Ave, New York, NY 10019',
                'description' => 'A historic luxury hotel located in the heart of Manhattan, overlooking Central Park.',
                'average_rate' => 4.5,
                'phone' => '+1 212-759-3000',
                'website' => 'https://www.theplazany.com/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Burj Al Arab',
                'location' => 'Jumeirah Beach Road, Dubai',
                'description' => 'The iconic sail-shaped hotel is known for its luxurious amenities, including a private beach, butler service, and helicopter transfers.',
                'average_rate' => 4.9,
                'phone' => '+971 4 301 7777',
                'website' => 'https://www.jumeirah.com/en/stay/dubai/burj-al-arab-jumeirah/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Belmond Hotel Caruso',
                'location' => 'Ravello, Italy - Piazza San Giovanni del Toro, 2',
                'description' => 'A luxurious hotel set in a restored 11th-century palace, offering panoramic views of the Amalfi Coast.',
                'average_rate' => 4.9,
                'phone' => '+39 089 858801',
                'website' => 'https://www.belmond.com/hotels/europe/italy/amalfi-coast/belmond-hotel-caruso/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The Peninsula',
                'location' => 'Salisbury Road, Tsim Sha Tsui, Kowloon, Hong Kong',
                'description' => 'The Peninsula is a 5-star hotel that is located in the heart of Hong Kong. It offers stunning views of Victoria Harbor and is known for its luxurious accommodations and world-class service.',
                'average_rate' => 4.8,
                'phone' => '+852 2920 2888',
                'website' => ' https://www.peninsula.com/en/hong-kong',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The Langham',
                'location' => ' London, UK - 1c Portland Pl, Marylebone',
                'description' => ' A luxurious hotel housed in a Victorian building, offering opulent rooms and suites and a Michelin-starred restaurant.',
                'average_rate' => 4.7,
                'phone' => '+44 20 7636 1000',
                'website' => 'https://www.langhamhotels.com/en/the-langham/london/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The Plaza Hotel',
                'location' => 'New York City, USA - 768 5th Ave, New York, NY 10019',
                'description' => 'A historic luxury hotel located in the heart of Manhattan, overlooking Central Park.',
                'average_rate' => 4.5,
                'phone' => '+1 212-759-3000',
                'website' => 'https://www.theplazany.com/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Four Seasons Resort Bali at Sayan',
                'location' => 'Ubud, Bali, Indonesia - Jl. Raya Sayan, Sayan, Kecamatan Ubud, Kabupaten Gianyar',
                'description' => 'A luxurious resort nestled in the heart of lush tropical rainforest, offering stunning views of the Ayung River.',
                'average_rate' => 4.8,
                'phone' => '+62 361 977577',
                'website' => 'https://www.fourseasons.com/sayan/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The St. Regis Bali Resort',
                'location' => 'Kawasan Pariwisata, Nusa Dua, Bali, Indonesia',
                'description' => 'A luxurious beachfront resort featuring a private beach, tropical gardens, and exceptional service.',
                'average_rate' => 4.9,
                'phone' => '+62 361 8478111',
                'website' => 'https://www.marriott.com/hotels/travel/dpsxr-the-st-regis-bali-resort/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Park Hyatt Tokyo',
                'location' => 'Tokyo, Japan - 3-7-1-2 Nishi Shinjuku, Shinjuku City',
                'description' => 'A luxurious hotel located on the 39th to 52nd floors of a skyscraper, offering stunning views of Tokyo and Mount Fuji.',
                'average_rate' => 4.7,
                'phone' => '+81 3-5322-1234',
                'website' => 'https://www.hyatt.com/en-US/hotel/japan/park-hyatt-tokyo/tyoph',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Waldorf Astoria Maldives Ithaafushi',
                'location' => 'South Malé Atoll, Republic of Maldives',
                'description' => 'A luxurious resort located on a private island, offering overwater villas, white sandy beaches, and a variety of dining and recreational activities.',
                'average_rate' => 4.9,
                'phone' => '+960 4-000300',
                'website' => 'https://www.hilton.com/en/hotels/mlewawaldorf-astoria-maldives-ithaafushi/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Belmond Hotel Caruso',
                'location' => 'Ravello, Italy - Piazza San Giovanni del Toro, 2',
                'description' => 'A luxurious hotel set in a restored 11th-century palace with breathtaking views of the Amalfi Coast.',
                'average_rate' => 4.9,
                'phone' => '+39 089 858801',
                'website' => 'https://www.belmond.com/hotels/europe/italy/amalfi-coast/belmond-hotel-caruso/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Shangri-La Hotel, Paris',
                'location' => 'Paris, France - 10 Avenue d Iéna',
                'description' => 'A luxurious hotel housed in a former palace with stunning views of the Eiffel Tower, offering Michelin-starred dining and a tranquil spa.',
                'average_rate' => 4.8,
                'phone' => '+33 1 53 67 19 98',
                'website' => 'https://www.shangri-la.com/paris/shangrila/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Aman Tokyo',
                'location' => 'Tokyo, Japan - 1-5-6 Otemachi, Chiyoda City',
                'description' => 'A luxurious hotel located in the heart of Tokyo, offering panoramic city views, a serene spa, and exquisite dining experiences.',
                'average_rate' => 4.9,
                'phone' => '+81 3-5224-3333',
                'website' => 'https://www.aman.com/resorts/aman-tokyo',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The Ritz-Carlton, Hong Kong',
                'location' => 'International Commerce Centre, Hong Kong - 1 Austin Road West, Kowloon',
                'description' => 'A luxurious hotel located on the top floors of the tallest building in Hong Kong, offering breathtaking views of the city and Victoria Harbour.',
                'average_rate' => 4.8,
                'phone' => '+852 2263 2263',
                'website' => 'https://www.ritzcarlton.com/en/hotels/china/hong-kong',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The Ritz-Carlton, Hong Kong',
                'location' => 'International Commerce Centre, Hong Kong - 1 Austin Road West, Kowloon',
                'description' => 'A luxurious hotel located on the top floors of the tallest building in Hong Kong, offering breathtaking views of the city and Victoria Harbour.',
                'average_rate' => 4.8,
                'phone' => '+852 2263 2263',
                'website' => 'https://www.ritzcarlton.com/en/hotels/china/hong-kong',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The Siam Hotel',
                'location' => 'Bangkok, Thailand - 3/2 Thanon Khao, Vachirapayabal, Dusit',
                'description' => 'A luxurious urban resort inspired by the golden age of 19th-century Siam, offering beautiful antiques, lush gardens, and a serene spa.',
                'average_rate' => 4.9,
                'phone' => '+66 2 206 6999',
                'website' => 'https://www.thesiamhotel.com/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The Brando',
                'location' => 'Tetiaroa, French Polynesia',
                'description' => 'A luxurious eco-resort located on a private island in the heart of the South Pacific, offering pristine beaches, crystal-clear waters, and a focus on sustainability.',
                'average_rate' => 4.9,
                'phone' => '+689 40 86 51 78',
                'website' => 'https://www.thebrando.com/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The Ritz-Carlton, Tokyo',
                'location' => 'Tokyo, Japan - 9-7-1 Akasaka, Minato-ku',
                'description' => 'A luxurious hotel located in the heart of Tokyo, offering stunning city views, Michelin-starred dining, and a tranquil spa.',
                'average_rate' => 4.8,
                'phone' => '+81 3-3423-8000',
                'website' => 'https://www.ritzcarlton.com/en/hotels/japan/tokyo',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The Brando',
                'location' => 'Tetiaroa, French Polynesia',
                'description' => 'A luxurious eco-resort located on a private island in the heart of the South Pacific, offering pristine beaches, crystal-clear waters, and a focus on sustainability.',
                'average_rate' => 4.9,
                'phone' => '+689 40 86 51 78',
                'website' => 'https://www.thebrando.com/',
                'room_price' => 1000,
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
        ];
        DB::table('hotels')->insert($data);
    }
}
