<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestaurantsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [
            [
                'name' => 'Osteria Francescana',
                'location' => 'Modena, Italy',
                'description' => 'A three-Michelin-starred restaurant run by chef Massimo Bottura, known for its innovative Italian cuisine.',
                'average_rate' => '4.9',
                'phone' => '+39 059 223912',
                'website' => 'www.osteriafrancescana.it',
                'average_price' => '250',
                'table_price' => '425',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,

            ],
            [
                'name' => 'Eleven Madison Park',
                'location' => 'New York City, USA',
                'description' => 'A three-Michelin-starred restaurant run by chef Daniel Humm, known for its modern American cuisine.',
                'average_rate' => '4.8',
                'phone' => '+1 212-889-0905',
                'website' => 'www.elevenmadisonpark.com',
                'average_price' => '335',
                'table_price' => '500',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Mirazur',
                'location' => 'Menton, France',
                'description' => 'A three-Michelin-starred restaurant run by chef Mauro Colagreco, known forits Mediterranean cuisine with a focus on local produce.',
                'average_rate' => '4.7',
                'phone' => '+33 4 92 41 86 86',
                'website' => 'www.mirazur.fr',
                'average_price' => '250',
                'table_price' => '375',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Gaggan',
                'location' => 'Bangkok, Thailand',
                'description' => 'A two-Michelin-starred restaurant run by chef Gaggan Anand, known for its progressive Indian cuisine.',
                'average_rate' => '4.9',
                'phone' => '+66 2 652 1700',
                'website' => 'www.eatatgaggan.com',
                'average_price' => '8000',
                'table_price' => '12000',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Central',
                'location' => 'Lima, Peru',
                'description' => 'A two-Michelin-starred restaurant run by chef Virgilio Martinez, known for its modern Peruvian cuisine.',
                'average_rate' => '4.8',
                'phone' => '+51 1 242 8515',
                'website' => 'centralrestaurante.com.pe',
                'average_price' => '600',
                'table_price' => '900',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Asador Etxebarri',
                'location' => 'Atxondo, Spain',
                'description' => 'A one-Michelin-starred restaurant run by chef Victor Arginzoniz, known for its wood-fired grilled meats and vegetables.',
                'average_rate' => '4.8',
                'phone' => '+34 946 583 042',
                'website' => 'asadoretxebarri.com',
                'average_price' => '200',
                'table_price' => '300',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Mugaritz',
                'location' => 'San Sebastian, Spain',
                'description' => 'A two-Michelin-starred restaurant run by chef Andoni Luis Aduriz, known for its experimental and avant-garde cuisine.',
                'average_rate' => '4.7',
                'phone' => '+34 943 522 455',
                'website' => 'www.mugaritz.com',
                'average_price' => '250',
                'table_price' => '400',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Attica',
                'location' => 'Melbourne, Australia',
                'description' => 'A three-Michelin-starred restaurant run by chef Ben Shewry, known for its modern Australian cuisine.',
                'average_rate' => '4.9',
                'phone' => '+61 3 9525 3155',
                'website' => 'attica.com.au',
                'average_price' => '300',
                'table_price' => '450',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Quintonil',
                'location' => 'Mexico City, Mexico',
                'description' => 'A one-Michelin-starred restaurant run by chef Jorge Vallejo, known for its contemporary Mexican cuisine.',
                'average_rate' => '4.8',
                'phone' => '+52 55 5280 1660',
                'website' => 'quintonil.com',
                'average_price' => '1500',
                'table_price' => '2000',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The Test Kitchen',
                'location' => 'Cape Town, South Africa',
                'description' => 'A one-Michelin-starred restaurant run by chef Luke Dale-Roberts, known for its modern South African cuisine.',
                'average_rate' => '4.8',
                'phone' => '+27 21 447 2337',
                'website' => 'thetestkitchen.co.za',
                'average_price' => '1200',
                'table_price' => '1800',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Maido',
                'location' => 'Lima, Peru',
                'description' => 'A three-Michelin-starred restaurant run by chef Mitsuharu Tsumura, known for its Nikkei cuisine, a fusion of Japanese and Peruvian flavors.',
                'average_rate' => '4.8',
                'phone' => '+51 1 3135100',
                'website' => 'www.maido.pe',
                'average_price' => '350',
                'table_price' => '525',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Blue Hill at Stone Barns',
                'location' => 'Pocantico Hills, USA',
                'description' => 'A one-Michelin-starred restaurant run by chef Dan Barber, known for its farm-to-table cuisine featuring ingredients from its own farm.',
                'average_rate' => '4.7',
                'phone' => '+1 914-366-9600',
                'website' => 'www.bluehillfarm.com',
                'average_price' => '278',
                'table_price' => '400',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Pujol',
                'location' => 'Mexico City, Mexico',
                'description' => 'A one-Michelin-starred restaurant run by chef Enrique Olvera, known for its contemporary Mexican cuisine.',
                'average_rate' => '4.7',
                'phone' => '+52 55 5545 4111',
                'website' => 'www.pujol.com.mx',
                'average_price' => '1200',
                'table_price' => '1800',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Azurmendi',
                'location' => 'Larrabetzu, Spain',
                'description' => 'A three-Michelin-starred restaurant run by chef Eneko Atxa, known for its sustainable and innovative Basque cuisine.',
                'average_rate' => '4.8',
                'phone' => '+34 944 55 88 66',
                'website' => 'www.azurmendi.restaurant',
                'average_price' => '250',
                'table_price' => '350',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Alinea',
                'location' => 'Chicago, USA',
                'description' => 'A three-Michelin-starred restaurant run by chef Grant Achatz, known for its avant-garde and experimental cuisine.',
                'average_rate' => '4.8',
                'phone' => '+1 312-867-0110',
                'website' => 'alinearestaurant.com',
                'average_price' => '385',
                'table_price' => '550',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'The Ledbury',
                'location' => 'London, UK',
                'description' => 'A two-Michelin-starred restaurant run by chef Brett Graham, known for its modern Europeancuisine with a focus on British ingredients.',
                'average_rate' => '4.7',
                'phone' => '+44 20 7792 9090',
                'website' => 'www.theledbury.com',
                'average_price' => '200',
                'table_price' => '325',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Geranium',
                'location' => 'Copenhagen, Denmark',
                'description' => 'A three-Michelin-starred restaurant run by chef Rasmus Kofoed, known for its contemporary Nordic cuisine.',
                'average_rate' => '4.7',
                'phone' => '+45 69 96 00 20',
                'website' => 'geranium.dk',
                'average_price' => '3000',
                'table_price' => '4500',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Septime',
                'location' => 'Paris, France',
                'description' => 'A one-Michelin-starred restaurant run by chef Bertrand Grébaut, known for its contemporary French cuisine.',
                'average_rate' => '4.7',
                'phone' => '+33 1 43 67 38 29',
                'website' => 'www.septime-charonne.fr',
                'average_price' => '80',
                'table_price' => '120',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Narisawa',
                'location' => 'Tokyo, Japan',
                'description' => 'A two-Michelin-starred restaurant run by chef Yoshihiro Narisawa, known for its innovative and sustainable cuisine.',
                'average_rate' => '4.7',
                'phone' => '+81 3-5785-0799',
                'website' => 'www.narisawa-yoshihiro.com',
                'average_price' => '250',
                'table_price' => '300',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Le Bernardin',
                'location' => 'New York City, USA',
                'description' => 'A three-Michelin-starred restaurant run by chef Eric Ripert, known for its seafood-focused French cuisine.',
                'average_rate' => '4.8',
                'phone' => '+1 212-554-1515',
                'website' => 'www.le-bernardin.com',
                'average_price' => '180',
                'table_price' => '360',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
            [
                'name' => 'Ultraviolet by Paul Pairet',
                'location' => 'Shanghai, China',
                'description' => 'A three-Michelin-starred restaurant run by chef Paul Pairet, known for its multi-sensory dining experience.',
                'average_rate' => '4.8',
                'phone' => '+86 21 3467 9122',
                'website' => 'www.uvbypp.cc',
                'average_price' => '630',
                'table_price' => '840',
                'published_at' => Carbon::now()->addHours(3)->toDateTimeString(),
                'active' => true,
            ],
        ];

        DB::table('restaurants')->insert($data);
    }
}
