<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Training;
use Illuminate\Database\Seeder;

class TrainingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $category = Category::create([
            [
                'name_ar' => 'Laravel',
                'name_en' => 'Laravel',
                'name_du' => 'Laravel',
            ],
        ]);
        Training::insert([
            [
                'provider_id' => 1,
                'category_id' => $category->id,
                'title_ar' => 'Mastering Laravel 12',
                'title_en' => 'Mastering Laravel 12',
                'title_du' => 'Mastering Laravel 12',
                'about_ar' => 'Learn Laravel 12 from basics to advanced topics including authentication, authorization, and testing.',
                'about_en' => 'Learn Laravel 12 from basics to advanced topics including authentication, authorization, and testing.',
                'about_du' => 'Learn Laravel 12 from basics to advanced topics including authentication, authorization, and testing.',
                'cover' => 'covers/laravel_mastery.jpg',
                'price' => '199.99',
                'type_ar' => 'live',
                'type_en' => 'live',
                'type_du' => 'live',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
            [
                'provider_id' => 2,
                'category_id' => $category->id,
                'title_ar' => 'Flutter App Development',
                'title_en' => 'Flutter App Development',
                'title_du' => 'Flutter App Development',
                'about_ar' => 'A comprehensive course on building high-performance mobile apps with Flutter and Dart.',
                'about_en' => 'A comprehensive course on building high-performance mobile apps with Flutter and Dart.',
                'about_du' => 'A comprehensive course on building high-performance mobile apps with Flutter and Dart.',
                'cover' => 'covers/flutter_app.jpg',
                'price' => '149.99',
                'type_ar' => 'recorded',
                'type_en' => 'recorded',
                'type_du' => 'recorded',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
            [
                'provider_id' => 3,
                'category_id' => $category->id,
                'title_ar' => 'JavaScript Full Stack Bootcamp',
                'title_en' => 'JavaScript Full Stack Bootcamp',
                'title_du' => 'JavaScript Full Stack Bootcamp',
                'about_ar' => 'Become a full-stack developer using JavaScript with Node.js, React, and Next.js.',
                'about_en' => 'Become a full-stack developer using JavaScript with Node.js, React, and Next.js.',
                'about_du' => 'Become a full-stack developer using JavaScript with Node.js, React, and Next.js.',
                'cover' => 'covers/js_fullstack.jpg',
                'price' => '299.99',
                'type_ar' => 'live',
                'type_en' => 'live',
                'type_du' => 'live',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
            [
                'provider_id' => 4,
                'category_id' => $category->id,
                'title_ar' => 'Python for Data Science',
                'title_en' => 'Python for Data Science',
                'title_du' => 'Python for Data Science',
                'about_ar' => 'An in-depth guide to using Python for data analysis, visualization, and machine learning.',
                'about_en' => 'An in-depth guide to using Python for data analysis, visualization, and machine learning.',
                'about_du' => 'An in-depth guide to using Python for data analysis, visualization, and machine learning.',
                'cover' => 'covers/python_data_science.jpg',
                'price' => '249.99',
                'type_ar' => 'recorded',
                'type_en' => 'recorded',
                'type_du' => 'recorded',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
            [
                'provider_id' => 5,
                'category_id' => $category->id,
                'title_ar' => 'DevOps with Docker & Kubernetes',
                'title_en' => 'DevOps with Docker & Kubernetes',
                'title_du' => 'DevOps with Docker & Kubernetes',
                'about_ar' => 'Learn how to use Docker and Kubernetes to streamline development and deployment processes.',
                'about_en' => 'Learn how to use Docker and Kubernetes to streamline development and deployment processes.',
                'about_du' => 'Learn how to use Docker and Kubernetes to streamline development and deployment processes.',
                'cover' => 'covers/devops_docker_k8s.jpg',
                'price' => '199.99',
                'type_ar' => 'live',
                'type_en' => 'live',
                'type_du' => 'live',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
            [
                'provider_id' => 1,
                'category_id' => $category->id,
                'title_ar' => 'React Native Mobile Apps',
                'title_en' => 'React Native Mobile Apps',
                'title_du' => 'React Native Mobile Apps',
                'about_ar' => 'Build cross-platform mobile apps using React Native with TypeScript.',
                'about_en' => 'Build cross-platform mobile apps using React Native with TypeScript.',
                'about_du' => 'Build cross-platform mobile apps using React Native with TypeScript.',
                'cover' => 'covers/react_native.jpg',
                'price' => '179.99',
                'type_ar' => 'recorded',
                'type_en' => 'recorded',
                'type_du' => 'recorded',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
            [
                'provider_id' => 2,
                'category_id' => $category->id,
                'title_ar' => 'Cloud Computing with AWS',
                'title_en' => 'Cloud Computing with AWS',
                'title_du' => 'Cloud Computing with AWS',
                'about_ar' => 'Explore AWS services and how to build and deploy applications in the cloud.',
                'about_en' => 'Explore AWS services and how to build and deploy applications in the cloud.',
                'about_du' => 'Explore AWS services and how to build and deploy applications in the cloud.',
                'cover' => 'covers/aws_cloud.jpg',
                'price' => '299.99',
                'type_ar' => 'live',
                'type_en' => 'live',
                'type_du' => 'live',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
            [
                'provider_id' => 3,
                'category_id' => $category->id,
                'title_ar' => 'Machine Learning Masterclass',
                'title_en' => 'Machine Learning Masterclass',
                'title_du' => 'Machine Learning Masterclass',
                'about_ar' => 'From beginner to expert in machine learning with hands-on projects.',
                'about_en' => 'From beginner to expert in machine learning with hands-on projects.',
                'about_du' => 'From beginner to expert in machine learning with hands-on projects.',
                'cover' => 'covers/ml_masterclass.jpg',
                'price' => '349.99',
                'type_ar' => 'recorded',
                'type_en' => 'recorded',
                'type_du' => 'recorded',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
            [
                'provider_id' => 4,
                'category_id' => $category->id,
                'title_ar' => 'Web Development with Next.js',
                'title_en' => 'Web Development with Next.js',
                'title_du' => 'Web Development with Next.js',
                'about_ar' => 'Master server-side rendering and static site generation with Next.js.',
                'about_en' => 'Master server-side rendering and static site generation with Next.js.',
                'about_du' => 'Master server-side rendering and static site generation with Next.js.',
                'cover' => 'covers/nextjs_webdev.jpg',
                'price' => '249.99',
                'type_ar' => 'live',
                'type_en' => 'live',
                'type_du' => 'live',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
            [
                'provider_id' => 5,
                'category_id' => $category->id,
                'title_ar' => 'Mobile Backend with Laravel',
                'title_en' => 'Mobile Backend with Laravel',
                'title_du' => 'Mobile Backend with Laravel',
                'about_ar' => 'Develop powerful backends for mobile applications using Laravel 12.',
                'about_en' => 'Develop powerful backends for mobile applications using Laravel 12.',
                'about_du' => 'Develop powerful backends for mobile applications using Laravel 12.',
                'cover' => 'covers/laravel_backend.jpg',
                'price' => '199.99',
                'type_ar' => 'recorded',
                'type_en' => 'recorded',
                'type_du' => 'recorded',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],

            [
                'provider_id' => 2,
                'category_id' => $category->id,
                'title_ar' => 'Cloud Computing with Mega',
                'title_en' => 'Cloud Computing with Mega',
                'title_du' => 'Cloud Computing with Mega',
                'about_ar' => 'Explore AWS services and how to build and deploy applications in the cloud.',
                'about_en' => 'Explore AWS services and how to build and deploy applications in the cloud.',
                'about_du' => 'Explore AWS services and how to build and deploy applications in the cloud.',
                'cover' => 'covers/mega_cloud.jpg',
                'price' => '299.99',
                'type_ar' => 'live',
                'type_en' => 'live',
                'type_du' => 'live',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
            [
                'provider_id' => 3,
                'category_id' => $category->id,
                'title_ar' => 'ML Masterclass',
                'title_en' => 'ML Masterclass',
                'title_du' => 'ML Masterclass',
                'about_ar' => 'From beginner to expert in machine learning with hands-on projects.',
                'about_en' => 'From beginner to expert in machine learning with hands-on projects.',
                'about_du' => 'From beginner to expert in machine learning with hands-on projects.',
                'cover' => 'covers/ML.jpg',
                'price' => '349.99',
                'type_ar' => 'recorded',
                'type_en' => 'recorded',
                'type_du' => 'recorded',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
            [
                'provider_id' => 4,
                'category_id' => $category->id,
                'title_ar' => 'Web Development with HTML',
                'title_en' => 'Web Development with HTML',
                'title_du' => 'Web Development with HTML',
                'about_ar' => 'Master server-side rendering and static site generation with Next.js.',
                'about_en' => 'Master server-side rendering and static site generation with Next.js.',
                'about_du' => 'Master server-side rendering and static site generation with Next.js.',
                'cover' => 'covers/HTML.jpg',
                'price' => '249.99',
                'type_ar' => 'live',
                'type_en' => 'live',
                'type_du' => 'live',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
            [
                'provider_id' => 5,
                'category_id' => $category->id,
                'title_ar' => 'Mobile Frontend with flutter',
                'title_en' => 'Mobile Frontend with flutter',
                'title_du' => 'Mobile Frontend with flutter',
                'about_ar' => 'Develop powerful backends for mobile applications using Laravel 12.',
                'about_en' => 'Develop powerful backends for mobile applications using Laravel 12.',
                'about_du' => 'Develop powerful backends for mobile applications using Laravel 12.',
                'cover' => 'covers/flutter_frontend.jpg',
                'price' => '199.99',
                'type_ar' => 'recorded',
                'type_en' => 'recorded',
                'type_du' => 'recorded',
                'created_at' => now(),
                'updated_at' => now(),
                'language' => 'en',
            ],
        ]);
    }
}
